version: '3.7'
services:
  coverage:
    build:
      context: .
      dockerfile: ./test/Dockerfile
    command: npm run coverage
    environment:
      API_PORT: 9004
      DEBUG: app-container*
      LOGGER_HTTP_REQUEST_ENABLED: "true"
      LOGGER_HTTP_RESPONSE_ENABLED: "true"
      LOGGER_HTTP_LEVEL: debug
      LOGGER_REPO_ENABLED: "false"
      NODE_CONFIG_DIR: /home/app/test/config
      NODE_ENV: test
    ports:
      - 9004:9004
    volumes:
      - ./coverage:/home/app/coverage
      - ./src:/home/app/src
      - ./test:/home/app/test
      - ./package.json:/home/app/package.json
      - /home/app/node_modules
